### ISSUE TITLE
LOD search value slider seems to cause issues 

### ISSUE THREAD

**Issue by qlee01** [Unity-Technologies/com.unity.demoteam.hair#54] opened 2023-03-13 12:09 UTC
Following observations while using the LOD search value slider:
- At 0 the simulation is not active, Hair is rendered in weird way (seems to have become even weirder with later updates)
- if changing the value it seems to break certain strands from being rendered. Correct behavior can sometime be restored by setting the value to 0 and then back again to higher value. This also happens while being used via API.
- tbh the whole concept of the slider is not 100% clear. The LOD search value seems to be a LOD for the simulation quality. It seems to work in discrete steps, not continuous.

**Comment by fuglsang** [comment] 2023-03-15 20:14
Thanks for reporting this. The weird behaviour you mention was a regression due to recent updates -- I'm about to push a fix for this regression.

To answer your question about the concept of the slider: The slider is basically the "manual" mode for selecting a particular level of detail. The value of the slider can be interpreted as 0 being "none of the strands", and 1 being "all of the strands". Based on the levels of detail present in (and generated via the "LOD Clusters" option in) the referenced assets, the system will pick (and optionally blend between) those levels of detail that best represent the value of the slider. Blending is toggled via the "LOD Blending" option. Automatic LOD selection will come later.

**Closed** 2023-03-15 20:22 UTC
Labels: bug
