### ISSUE TITLE
Fails in Unity 2020.3.37f1 HDRP

### ISSUE THREAD

**Issue by EddieSoloProjects** [Unity-Technologies/com.unity.demoteam.hair#2] opened 2022-08-13 11:05 UTC
In Unity 2020.3.37f1 (64-bit) this package throws an error in HDRP. It say you have the same code in 2 places. And your sample scene turns black.

**Comment by fuglsang** [comment] 2022-12-06 20:09
Hi, and thank you for the report. Unfortunately I was not able to reproduce this error with (*any of the available versions of) HDRP and Unity 2020.3.37f1, so I am closing this issue for now. Please submit a new issue if the problem persists, including steps to reproduce the error.

**Closed by fuglsang** 2022-12-06 20:09 UTC
